import Link from "next/link";

export default function ProductionLotsEntryPage() {
  return (
    <main className="min-h-screen bg-black p-8 text-white">
      <p className="text-xs uppercase tracking-[0.35em] text-white/40">
        Production / Lot Code Control
      </p>

      <h1 className="mt-4 text-3xl font-semibold">Production Lot Codes</h1>

      <p className="mt-3 max-w-2xl text-white/60">
        Production lot codes are system-generated by OmniLytix from structured production data.
      </p>

      <Link
        href="/receive/lots"
        className="mt-6 inline-flex rounded-2xl border border-white/15 bg-white px-5 py-3 text-sm font-semibold text-black"
      >
        Open Production Lot Code Generator
      </Link>
    </main>
  );
}